### ISSUE TITLE
Can I refer this repository to create openldap docker image in private cloud which isn't built in Openshift?

### ISSUE THREAD

**Issue by ozbillwang** [openshift/openldap#13]
I need change and customise some codes to adapt for our environment. But the "DISCLAIMER" part in README confused me if I still can use it or not.

Can I refer this repository to create openldap docker image in private cloud which isn't built in Openshift?

**Comment by deads2k** [comment]
As long as you're within the license (https://github.com/openshift/openldap/blob/master/LICENSE), you may re-use this as you see fit.

The disclaimer is to make it clear that this image is **not** considered production ready and is **not**  supported.  We needed an openldap server to prove that our LDAP integration worked and we chose to expose it to provide a tangible example of how OpenShift can interact with LDAP, but we are not LDAP admins.

**Comment by ozbillwang** [comment]
This is open source website, I am not sure this disclaimer makes sense any more. 

Anyway, thanks for the updates. It can be closed.
