### ISSUE TITLE
Allows to run with non privileged ports (> 1024)

### ISSUE THREAD

**Issue by akram** [openshift/openldap#15]
by default it runs on port 389,
 ca we allows it to run with non privileged ports (> 1024) ?

**Comment by stevekuznetsov** [comment]
This image is explicitly created to facilitate testing for OpenShift. You should not use this image for production environments and this image is not supported in any configuration. If you would like to make a PR to help this to run on non-privileged ports and the changes do not break Origin tests, I am happy to merge it, but please keep the above warnings in mind.

**Comment by opm22** [comment]
I imagine you can accomplish what you need just by using expose feature on docker command, no other change needed. 

`docker run ... -p <2389>:389 ...`

ref.: https://docs.docker.com/engine/reference/run/#expose-incoming-ports
